Repository metabrainz/picard, pull requests merged in 2018-09, with the labels that each got.

#947 PICARD-1329: Fix saving iTunNORM tags to ID3
  picard/formats/id3.py
  test/test_formats.py
Labels: Bug fix

#950 [2.0.x] PICARD-1216: Attempt to attach to console on Windows
  tagger.py
Labels: Bug fix, backport

#951 [2.0.x] PICARD-1326: FLAC: Preserve waveformatextensible_channel_mask when clearing tags
  picard/formats/vorbis.py
  test/data/test.flac
  test/test_formats.py
Labels: Bug fix, backport

#948 [2.0.x] PICARD-1327: Fix loading TAK files
  picard/formats/mutagenext/tak.py
  test/data/test.tak
  test/test_formats.py
Labels: Bug fix, backport

#952 [2.0.x] PICARD-1329: Fix saving iTunNORM tags to ID3
  picard/formats/id3.py
  test/test_formats.py
Labels: Bug fix, backport

#953 PICARD-1331: Fix crash when plugin installation fails
  picard/plugin.py
Labels: Bug fix

#945 PICARD-1328: Fix loading OptimFROG files
  picard/formats/apev2.py
  test/data/test.ofr
  test/data/test.ofs
  test/test_formats.py
Labels: Bug fix

#955 [2.0.x] PICARD-1331: Fix crash when plugin installation fails
  picard/plugin.py
Labels: Bug fix, backport

#949 [2.0.x] PICARD-1328: Fix loading OptimFROG files
  picard/formats/apev2.py
  test/data/test.ofr
  test/data/test.ofs
  test/test_formats.py
Labels: Bug fix, backport

#954 PICARD-1332: When unmatching a file restore deleted tags from origina…
  picard/file.py
  picard/metadata.py
  picard/track.py
  test/test_metadata.py
Labels: Bug fix, Test please

#959 PICARD-1336: For MP4 integer tags were not marked as supported
  picard/formats/mp4.py
  test/test_formats.py
Labels: Bug fix

#960 PICARD-1112: Clear deleted tags after saving file
  picard/file.py
  picard/metadata.py
  test/test_metadata.py
Labels: Bug fix

#964 PICARD-1339: Remove O(n^2) complexity when deleting files
  picard/cluster.py
  picard/tagger.py
  picard/track.py
Labels: Bug fix

#969 PICARD-1281: Drop deprecated CFBundleGetInfoString from info.plist
  picard.spec
Labels: do not merge yet
