Repository metabrainz/picard, pull requests merged in 2023-08, with the labels that each got.

#2266 PICARD-1815: Add option to notify user at startup if plugin updates are available
  picard/pluginmanager.py
  picard/profile.py
  picard/ui/mainwindow.py
  picard/ui/options/general.py
  picard/ui/ui_options_general.py
  ui/options_general.ui
Labels: Feature

#2270 PICARD-2696: Fix file deletion when shift-dropping files on Windows
  picard/ui/coverartbox.py
  picard/ui/itemviews.py
Labels: Bug fix

#2274 PICARD-2713: Fix --stand-alone-instance handling
  picard/util/pipe.py
Labels: Bug fix

#2273 PICARD-2710: Fix no loading files on low CPU systems
  picard/tagger.py
Labels: Bug fix

#2275 PICARD-2186: Fix detection of running app in Windows (un)installer
  installer/picard-setup.nsi.in
Labels: Bug fix

#2279 PICARD-2715: Show plugins with updates and add button to open plugin options window
  picard/pluginmanager.py
  picard/ui/mainwindow.py
Labels: Feature

#2282 PICARD-2717: Send SHOW command by default to existing instance
  picard/util/pipe.py
Labels: Feature

#2281 PICARD-2720: Add .desktop file action to explicitly open new window
  org.musicbrainz.Picard.desktop
Labels: Feature

#2285 Add note about contributing to user documentation
  CONTRIBUTING.md
Labels: Doc update
