Repository metabrainz/picard, pull requests merged in 2024-05, with the labels that each got.

#2447 PICARD-2884: Show tooltips for more file / track icon types
  picard/ui/itemviews.py
Labels: Bug fix, Feature

#2450 Mainwindow actions: move to their own file, and overall cleanup
  picard/acoustid/manager.py
  picard/cluster.py
  picard/const/defaults.py
  picard/options.py
  picard/ui/enums.py
  picard/ui/itemviews.py
  picard/ui/mainwindow/__init__.py
  picard/ui/mainwindow/actions.py
  picard/ui/options/interface_toolbar.py
  picard/ui/options/renaming.py
  picard/ui/options/tags.py
  picard/ui/util.py
  test/test_acoustidmanager.py
Labels: Refactoring

#2452 Simplify toolbar editor
  picard/ui/options/interface_toolbar.py
Labels: Refactoring

#2456 QMouseEvent.globalPos() is deprecated -> replace with globalPosition(…
  picard/ui/widgets/tristatesortheaderview.py
Labels: Bug fix

#2462 BaseTreeView, FileTreeView: introduce property `default_drop_target`
  picard/ui/itemviews.py
Labels: Refactoring

#2463 Itemviews headers refactoring
  picard/__init__.py
  picard/config_upgrade.py
  picard/ui/itemviews.py
  picard/ui/widgets/tristatesortheaderview.py
  test/test_config_upgrade.py
Labels: Refactoring

#2464 Itemviews basetreeview cleanup
  picard/ui/itemviews.py
Labels: Refactoring

#2469 Move BaseTreeView and associated methods to its own file
  picard/ui/itemviews/__init__.py
  picard/ui/itemviews/basetreeview.py
Labels: Refactoring

#2476 Metadatabox cleanup
  picard/ui/edittagdialog.py
  picard/ui/metadatabox.py
  test/test_metadatabox.py
Labels: Refactoring

#2479 Infodialog cleanup
  picard/ui/infodialog.py
Labels: Refactoring

#2485 Rename from generic Ui_Dialog to proper Ui_CDLookupDialog and Ui_Opti…
  picard/ui/cdlookup.py
  picard/ui/forms/ui_cdlookup.py
  picard/ui/forms/ui_options.py
  picard/ui/options/dialog.py
  ui/cdlookup.ui
  ui/options.ui
Labels: Refactoring

#2481 Infodialog cleanup2
  picard/coverart/image.py
  picard/coverart/utils.py
  picard/ui/infodialog.py
  test/test_coverart_image.py
Labels: Refactoring

#2484 Collection menu cleanup
  picard/ui/collectionmenu.py
Labels: Refactoring

#2489 Add missing self.tagger initializations
  picard/ui/coverartbox.py
Labels: Bug fix

#2493 PICARD-2910: Fix AttributeError: 'ScriptEditorDialog' object has no attribute 'uns…
  picard/ui/mainwindow/__init__.py
Labels: Backport

#2495 Introduce ProgressStatus class and use an instance of it to pass valu…
  picard/ui/infostatus.py
  picard/ui/mainwindow/__init__.py
  picard/ui/statusindicator.py
Labels: Refactoring

#2494 match -> match_: match is a statement in Python 3.10+
  installer/i18n/nshutil.py
  picard/cluster.py
  picard/script/functions.py
  picard/ui/coverartbox.py
  picard/ui/options/plugins.py
  picard/ui/tagsfromfilenames.py
  picard/util/__init__.py
  picard/util/tags.py
  picard/version.py
  test/test_metadata.py
Labels: Refactoring

#2492 PICARD-2912: Script editor syntax highlighting fixes and improvements
  picard/ui/widgets/scripttextedit.py
Labels: Bug fix, Backport

#2488 Image list cleanup
  picard/album.py
  picard/cluster.py
  picard/file.py
  picard/item.py
  picard/metadata.py
  picard/track.py
  picard/ui/coverartbox.py
  picard/util/imagelist.py
  test/test_imagelist.py
Labels: Refactoring

#2500 Introduce MetadataItem.suspend_metadata_images_update context manager
  picard/album.py
  picard/item.py
  picard/ui/coverartbox.py
Labels: Refactoring
