Repository metabrainz/picard, pull requests merged in 2024-01, with the labels that each got.

#2351 PICARD-2584: Load recording if AcoustId metadata is missing
  picard/acoustid/__init__.py
  picard/acoustid/json_helpers.py
  picard/acoustid/recordings.py
  test/test_acoustid.py
Labels: Feature

#2360 Do PyPI deployment with Trusted Publisher Management
  .github/workflows/package-pypi.yml
  .github/workflows/package.yml
Labels: Needs more work

#2361 PICARD-1685 : Add ~filesize variable
  picard/file.py
  picard/formats/wav.py
  picard/ui/infodialog.py
  picard/ui/itemviews.py
  test/formats/common.py
  test/formats/test_aac.py
  test/formats/test_ac3.py
  test/formats/test_apev2.py
  test/formats/test_asf.py
  test/formats/test_id3.py
  test/formats/test_midi.py
  test/formats/test_mp4.py
  test/formats/test_vorbis.py
  test/formats/test_wav.py
Labels: Feature, Doc update
