Repository metabrainz/picard, pull requests merged in 2024-06, with the labels that each got.

#2507 PICARD-2919: fix download of GIF images (and maybe others)
  picard/webservice/__init__.py
Labels: Bug fix, Backport

#2505 PICARD-2918: avoid exception if hash isn't found in _datafiles on exit
  picard/coverart/image.py
Labels: Bug fix, Backport

#2508 Refactor dataobj into item
  picard/album.py
  picard/cluster.py
  picard/dataobj.py
  picard/file.py
  picard/item.py
  picard/releasegroup.py
  picard/script/functions.py
  picard/tagger.py
  picard/track.py
  picard/ui/coverartbox.py
  picard/ui/infodialog.py
  picard/ui/itemviews/__init__.py
  picard/ui/mainwindow/__init__.py
  picard/ui/metadatabox.py
  picard/ui/searchdialog/track.py
  test/test_file.py
  test/test_item.py
  test/test_script.py
Labels: Refactoring

#2512 Drop PluginPriority in favor of a simple integer and add tests
  picard/extension_points/event_hooks.py
  picard/extension_points/metadata.py
  picard/plugin.py
  test/test_plugins.py
Labels: Refactoring

#2517 PICARD-2935: apply genre filters and threshold before selecting minimal usage
  picard/track.py
  test/test_taggenrefilter.py
  test/test_track.py
Labels: Bug fix, Backport

#2518 PICARD-2918: avoid exception if hash isn't found in _datafiles on exit (2.x)
  picard/coverart/image.py
Labels: Picard 2.x
