Repository metabrainz/picard, pull requests merged in 2025-05, with the labels that each got.

#2636 PICARD-3061: Add long descriptions to tags, display them in tooltips
  picard/const/__init__.py
  picard/options.py
  picard/ui/metadatabox/__init__.py
  picard/ui/widgets/scripttextedit.py
  picard/util/tags.py
  test/test_config.py
  test/test_options.py
  test/test_profiles.py
  test/test_util_tags.py
Labels: Feature

#2640 PICARD-3062: Add tag documentation to script editor help
  picard/ui/scripteditor/__init__.py
  picard/ui/widgets/scriptdocumentation.py
  picard/util/tags.py
  test/test_util_tags.py
Labels: Feature

#2644 PICARD-3066: Fix theme initialization and set generic accent color in dark mode
  picard/ui/theme.py
Labels: Experimental

#2647 Refactor tags
  picard/const/tags.py
  picard/file.py
  picard/formats/id3.py
  picard/metadata.py
  picard/tags/__init__.py
  picard/tags/preserved.py
  picard/tags/tagvar.py
  picard/ui/metadatabox/__init__.py
  picard/ui/metadatabox/edittagdialog.py
  picard/ui/metadatabox/tagdiff.py
  picard/ui/tagsfromfilenames.py
  picard/ui/widgets/scriptdocumentation.py
  picard/ui/widgets/scripttextedit.py
  picard/ui/widgets/taglisteditor.py
  test/formats/common.py
  test/test_file.py
  test/test_metadata.py
  test/test_preservedtags.py
  test/test_tags.py
  test/test_utils.py
Labels: Refactoring
